spring:
  profiles:
    active: development
---
server:
  port: 8080
  contextPath: /uaa

spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8080
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ 
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
    